# -*- coding: utf-8 -*-

"""Non-streaming Responses provider primitives."""

import json
import time
import uuid
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from loguru import logger

from kiro.config import KIRO_MAX_PAYLOAD_BYTES
from kiro.converters_core import KiroPayloadResult, build_kiro_payload
from kiro.converters_responses import ResponsesConversionError, ResponsesRequestIR
from kiro.models_responses import ResponsesRequest
from kiro.payload_guards import check_payload_size
from kiro.streaming_core import StreamResult, calculate_tokens_from_context_usage
from kiro.tokenizer import count_tokens, estimate_request_tokens
from kiro.utils import generate_conversation_id


@dataclass(frozen=True)
class ResponsesUsageEstimate:
    """Usage values and their internal measurement provenance."""

    input_tokens: int
    output_tokens: int
    total_tokens: int
    input_source: str
    output_source: str
    total_source: str
    reasoning_tokens: int = 0
    cached_tokens: Optional[int] = None

    def as_dict(self) -> Dict[str, Any]:
        """Serialize usage in the official Responses object shape."""
        usage: Dict[str, Any] = {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "output_tokens_details": {"reasoning_tokens": self.reasoning_tokens},
            "total_tokens": self.total_tokens,
        }
        if self.cached_tokens is not None:
            usage["input_tokens_details"] = {"cached_tokens": self.cached_tokens}
        return usage


def build_responses_kiro_payload(
    request_ir: ResponsesRequestIR,
    profile_arn: str,
    kiro_model_id: str,
) -> KiroPayloadResult:
    """Build the shared Kiro payload from a Responses IR.

    Args:
        request_ir: Protocol-specific Responses intermediate representation.
        profile_arn: AWS CodeWhisperer profile ARN for the selected account.
        kiro_model_id: Internal Kiro Model ID resolved for this account.

    Returns:
        The shared Kiro payload and any tool documentation generated by the
        common converter.
    """
    try:
        payload_result = build_kiro_payload(
            messages=request_ir.messages,
            system_prompt=request_ir.system_prompt,
            model_id=kiro_model_id,
            tools=request_ir.unified_tools,
            conversation_id=generate_conversation_id(),
            profile_arn=profile_arn,
            thinking_config=request_ir.thinking_config,
            allow_payload_trim=False,
        )
    except ResponsesConversionError:
        raise
    except (TypeError, ValueError) as exc:
        raise ResponsesConversionError(
            "Responses input cannot be represented by the Kiro payload; "
            "check tool definitions and replayed function-call arguments"
        ) from exc
    payload_size = check_payload_size(payload_result.payload)
    if payload_size > KIRO_MAX_PAYLOAD_BYTES:
        raise ResponsesConversionError(
            "Responses request exceeds the Kiro payload limit "
            f"({payload_size} > {KIRO_MAX_PAYLOAD_BYTES} bytes). "
            "Reduce the client-owned input history, inline images, or tool definitions and retry; "
            "KiroaaS did not trim or summarize the request."
        )
    return payload_result


def _count_output_tokens(result: StreamResult) -> int:
    """Estimate generated text and tool argument tokens."""
    generated_text = result.content + result.thinking_content
    output_tokens = count_tokens(generated_text)
    if result.tool_calls:
        tool_text = "".join(
            str((tool.get("function") or {}).get("name", ""))
            + str((tool.get("function") or {}).get("arguments", ""))
            for tool in result.tool_calls
        )
        output_tokens += count_tokens(tool_text)
    return output_tokens


def _extract_cached_tokens(result: StreamResult) -> Optional[int]:
    """Return an explicitly reported upstream cache count, when available."""
    if not isinstance(result.usage, dict):
        return None
    for key in ("cached_tokens", "cachedTokens", "cache_read_input_tokens"):
        value = result.usage.get(key)
        if isinstance(value, (int, float)) and value >= 0:
            return int(value)
    return None


def estimate_responses_usage(
    result: StreamResult,
    request_ir: ResponsesRequestIR,
    model_cache: Optional[Any],
    model: str,
) -> ResponsesUsageEstimate:
    """Estimate Responses usage from Kiro context data and the existing tokenizer.

    Kiro's ``usage`` event is credit metering rather than token accounting.
    The context percentage is therefore used when available for total tokens;
    the existing tokenizer supplies prompt and output fallbacks. The source of
    each estimate is logged without logging prompt, source, command, or tool
    result contents.

    Args:
        result: Fully collected Kiro stream result.
        request_ir: Converted request used for tokenizer estimation.
        model_cache: Account model cache, when available for context sizing.
        model: External model ID used for diagnostic attribution.

    Returns:
        Responses usage values and measurement provenance.
    """
    tokenizer_estimate = estimate_request_tokens(
        request_ir.tokenizer_messages,
        tools=request_ir.raw_tools,
        system_prompt=request_ir.system_prompt,
        apply_claude_correction=False,
    )
    input_tokens = tokenizer_estimate["total_tokens"]
    output_tokens = _count_output_tokens(result)
    input_source = "tokenizer"
    output_source = "tokenizer"
    total_source = "tokenizer"
    total_tokens = input_tokens + output_tokens

    if model_cache is not None and result.context_usage_percentage is not None:
        context_input, context_total, context_input_source, context_total_source = (
            calculate_tokens_from_context_usage(
                result.context_usage_percentage,
                output_tokens,
                model_cache,
                model,
            )
        )
        if context_total > 0:
            input_tokens = context_input
            total_tokens = context_total
            input_source = f"Kiro contextUsagePercentage ({context_input_source})"
            total_source = context_total_source

    logger.debug(
        "[Responses Usage] model={} input_tokens={} ({}), output_tokens={} ({}), "
        "total_tokens={} ({}), context_usage_present={}",
        model,
        input_tokens,
        input_source,
        output_tokens,
        output_source,
        total_tokens,
        total_source,
        result.context_usage_percentage is not None,
    )
    cached_tokens = _extract_cached_tokens(result)
    if cached_tokens is not None:
        logger.debug(
            "[Responses Usage] cached_tokens={} source=Kiro usage event",
            cached_tokens,
        )
    return ResponsesUsageEstimate(
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        total_tokens=total_tokens,
        input_source=input_source,
        output_source=output_source,
        total_source=total_source,
        reasoning_tokens=count_tokens(result.thinking_content),
        cached_tokens=cached_tokens,
    )


def _new_item_id(prefix: str) -> str:
    """Create a response-scoped output item identity."""
    return f"{prefix}_{uuid.uuid4().hex}"


def _new_request_scoped_call_id(
    response_id: str,
    output_index: int,
    used_call_ids: set[str],
) -> str:
    """Create a stable call ID for one missing upstream Tool Call ID.

    Args:
        response_id: Identity of the current HTTP Responses request.
        output_index: Stable position of the Tool Call in the Kiro result.
        used_call_ids: IDs already assigned in this response.

    Returns:
        A unique call ID scoped to this response and output position.
    """
    response_token = response_id.removeprefix("resp_")
    candidate = f"call_{response_token}_{output_index}"
    suffix = 1
    while candidate in used_call_ids:
        candidate = f"call_{response_token}_{output_index}_{suffix}"
        suffix += 1
    return candidate


def generate_response_id() -> str:
    """Create a new Responses identity for one HTTP request."""
    return f"resp_{uuid.uuid4().hex}"


def build_responses_object(
    request: ResponsesRequest,
    request_ir: ResponsesRequestIR,
    result: StreamResult,
    model_cache: Optional[Any],
    response_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Build one formal non-streaming Responses object.

    Empty generated messages are omitted. Tool calls are represented as
    ``function_call`` output items and retain their upstream call IDs, while
    missing IDs receive a new ID local to this response.

    Args:
        request: Original Responses request for echo fields.
        request_ir: Converted request for usage estimation.
        result: Fully collected Kiro stream result.
        model_cache: Account model cache, when available for context sizing.
        response_id: Optional request-scoped identity supplied by the route.

    Returns:
        A formal non-streaming Responses response object.
    """
    response_id = response_id or generate_response_id()
    output: List[Dict[str, Any]] = []

    if result.content:
        output.append(
            {
                "id": _new_item_id("msg"),
                "type": "message",
                "status": "completed",
                "role": "assistant",
                "content": [
                    {
                        "type": "output_text",
                        "text": result.content,
                        "annotations": [],
                    }
                ],
            }
        )

    seen_call_ids: set[str] = set()
    for output_index, tool in enumerate(result.tool_calls):
        function = tool.get("function") or {}
        if tool.get("_truncation_detected"):
            raise ResponsesConversionError(
                "Kiro returned truncated Tool Call arguments; retry the request "
                "or reduce the tool input and context"
            )
        call_id = tool.get("id")
        if tool.get("_generated_id") or not call_id:
            call_id = _new_request_scoped_call_id(
                response_id,
                output_index,
                seen_call_ids,
            )
        if not isinstance(call_id, str) or not call_id:
            raise ResponsesConversionError(
                "Kiro returned a Tool Call without a usable call_id"
            )
        if call_id in seen_call_ids:
            raise ResponsesConversionError(
                f"Kiro returned duplicate Tool Call call_id '{call_id}'; "
                "retry the request or report the upstream response"
            )
        seen_call_ids.add(call_id)
        name = function.get("name") or tool.get("name")
        if not isinstance(name, str) or not name:
            raise ResponsesConversionError(
                f"Kiro returned Tool Call '{call_id}' without a function name"
            )
        arguments = function.get("arguments")
        if arguments is None or arguments == "":
            arguments = "{}"
        elif isinstance(arguments, (dict, list)):
            arguments = json.dumps(arguments, ensure_ascii=False)
        elif not isinstance(arguments, str):
            raise ResponsesConversionError(
                f"Kiro returned malformed arguments for Tool Call '{call_id}'"
            )
        try:
            parsed_arguments = json.loads(arguments)
        except json.JSONDecodeError as exc:
            raise ResponsesConversionError(
                f"Kiro returned malformed arguments for Tool Call '{call_id}'"
            ) from exc
        if not isinstance(parsed_arguments, dict):
            raise ResponsesConversionError(
                f"Kiro returned non-object arguments for Tool Call '{call_id}'"
            )
        output.append(
            {
                "id": _new_item_id("fc"),
                "type": "function_call",
                "status": "completed",
                "call_id": call_id,
                "name": name,
                "arguments": arguments,
            }
        )

    usage = estimate_responses_usage(result, request_ir, model_cache, request.model)
    now = int(time.time())
    effort = (request.reasoning or {}).get("effort")
    return {
        "id": response_id,
        "object": "response",
        "created_at": now,
        "status": "completed",
        "background": False,
        "completed_at": now,
        "error": None,
        "incomplete_details": None,
        "input": [item.model_dump(exclude_none=True) for item in request.input]
        if isinstance(request.input, list)
        else request.input,
        "instructions": request.instructions,
        "max_output_tokens": request.max_output_tokens,
        "max_tool_calls": request.max_tool_calls,
        "model": request.model,
        "output": output,
        "parallel_tool_calls": request.parallel_tool_calls if request.parallel_tool_calls is not None else True,
        "previous_response_id": None,
        "prompt": None,
        "prompt_cache_key": request.prompt_cache_key,
        "reasoning": {"effort": effort, "summary": None},
        "reasoning_effort": effort,
        "safety_identifier": request.safety_identifier,
        "service_tier": None,
        "store": False,
        "temperature": request.temperature if request.temperature is not None else 1.0,
        "text": request.text or {"format": {"type": "text"}},
        "tool_choice": request.tool_choice or "auto",
        "tools": request.tools or [],
        "top_logprobs": None,
        "top_p": request.top_p if request.top_p is not None else 1.0,
        "truncation": "disabled",
        "usage": usage.as_dict(),
        "user": request.user,
        "metadata": request.metadata or {},
    }
